config/routes.rb
# == Route Map
#
#                           Prefix Verb   URI Pattern                                                                              Controller#Action
#                letter_opener_web        /letter_opener                                                                           LetterOpenerWeb::Engine
#                      sidekiq_web        /sidekiq                                                                                 Sidekiq::Web
#                             root GET    /                                                                                        posts#index
#                            login GET    /login(.:format)                                                                         sessions#new
#                                  POST   /login(.:format)                                                                         sessions#create
#                           logout DELETE /logout(.:format)                                                                        sessions#destroy
#                            users GET    /users(.:format)                                                                         users#index
#                                  POST   /users(.:format)                                                                         users#create
#                         new_user GET    /users/new(.:format)                                                                     users#new
#                             user GET    /users/:id(.:format)                                                                     users#show
#                    post_comments POST   /posts/:post_id/comments(.:format)                                                       comments#create
#                     edit_comment GET    /comments/:id/edit(.:format)                                                             comments#edit
#                          comment PATCH  /comments/:id(.:format)                                                                  comments#update
#                                  PUT    /comments/:id(.:format)                                                                  comments#update
#                                  DELETE /comments/:id(.:format)                                                                  comments#destroy
#                     search_posts GET    /posts/search(.:format)                                                                  posts#search
#                            posts GET    /posts(.:format)                                                                         posts#index
#                                  POST   /posts(.:format)                                                                         posts#create
#                         new_post GET    /posts/new(.:format)                                                                     posts#new
#                        edit_post GET    /posts/:id/edit(.:format)                                                                posts#edit
#                             post GET    /posts/:id(.:format)                                                                     posts#show
#                                  PATCH  /posts/:id(.:format)                                                                     posts#update
#                                  PUT    /posts/:id(.:format)                                                                     posts#update
#                                  DELETE /posts/:id(.:format)                                                                     posts#destroy
#              edit_mypage_account GET    /mypage/account/edit(.:format)                                                           mypage/accounts#edit
#                   mypage_account PATCH  /mypage/account(.:format)                                                                mypage/accounts#update
#                                  PUT    /mypage/account(.:format)                                                                mypage/accounts#update
#                mypage_activities GET    /mypage/activities(.:format)                                                             mypage/activities#index
# edit_mypage_notification_setting GET    /mypage/notification_setting/edit(.:format)                                              mypage/notification_settings#edit
#      mypage_notification_setting PATCH  /mypage/notification_setting(.:format)                                                   mypage/notification_settings#update
#                                  PUT    /mypage/notification_setting(.:format)                                                   mypage/notification_settings#update
#                            likes POST   /likes(.:format)                                                                         likes#create
#                             like DELETE /likes/:id(.:format)                                                                     likes#destroy
#                    relationships POST   /relationships(.:format)                                                                 relationships#create
#                     relationship DELETE /relationships/:id(.:format)                                                             relationships#destroy
#                    read_activity PATCH  /activities/:id/read(.:format)                                                           activities#read
#               rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
#        rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#               rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
#        update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#             rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create
#
# Routes for LetterOpenerWeb::Engine:
# clear_letters DELETE /clear(.:format)                 letter_opener_web/letters#clear
# delete_letter DELETE /:id(.:format)                   letter_opener_web/letters#destroy
#       letters GET    /                                letter_opener_web/letters#index
#        letter GET    /:id(/:style)(.:format)          letter_opener_web/letters#show
#               GET    /:id/attachments/:file(.:format) letter_opener_web/letters#attachment

# annotateで作成された
Rails.application.routes.draw do
  require 'sidekiq/web'
  # letter_openerを使用した画面の表示のために必要。localhost:3000/letter_openerでメールを確認することができる
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
    # localhost:3000/sidekiqでダッシュボードに繋がる
    mount Sidekiq::Web, at: '/sidekiq'
  end

  root to: 'posts#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users, only: %i[index new create show]
  # shallowオプション。show,edit,update,destroyのようにposts/:post_id/comments/:idを使うアクションのURLをcomments/:idという風に短くする。
  resources :posts, shallow: true do
    resources :comments, only: %i[create edit update destroy]
    # /posts/でurlを始めたい場合にcollectionオプションを使う。/posts/:id/でurlを始めたい場合は、memberオプションを使う。
    collection do
      get 'search'
    end
  end

  # namespaceはurlのパスとディレクトリ構成を変更する。マイページにいろいろ追加するので、マイページ用のディレクトリとurlを作る。
  namespace :mypage do
    # ログインユーザーにとってアカウント編集ページは一つしかないので、単一のresourceを使う。index用のルーティングは存在しない。
    resource :account, only: %i[edit update]
    resources :activities, only: %i[index]
    # 通知設定そのものは、ログインユーザーに対して一つしかないため単一リソースで定義する
    resource :notification_setting, only: %i[edit update]
  end

  resources :likes, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]

  # urlをactivities/:id/readのみに限定するため、onlyで絞る。
  resources :activities, only: [] do
    # memberオプションでactivities/:idというurlが生成される。この場合は、activitiesコントローラーのreadアクションにリクエストを送る。一つしかない場合は、このような書き方ができる。
    patch :read, on: :member
  end
end

app/views/shared/_before_login_header.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-white
  = link_to 'InstaClone', root_path, class: 'navbar-brand'
  button.navbar-toggler aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarTogglerDemo02" data-toggle="collapse" type="button"
    span.navbar-toggler-icon
  #navbarTogglerDemo02.collapse.navbar-collapse
    = render 'posts/search_form', search_form: @search_form
    ul.navbar-nav.mt-2.mt-lg-0
      li.nav-item
        = link_to 'ポスト一覧', posts_path, class: 'nav-link'
      li.nav-item
        = link_to 'ログイン', login_path, class: 'nav-link'

app/views/shared/_commented_to_own_post.html.slim
/ activity.read?でactivityオブジェクトのread属性がreadかどうか確認できる。enumによって追加されたメソッド。
= link_to read_activity_path(activity), class: "dropdown-item border-bottom #{'read' if activity.read?}", method: :patch do 
  = image_tag  activity.subject.user.avatar.url, class: 'rounded-circle mr-1', size: '30x30'
  object
    = link_to activity.subject.user.name, user_path(activity.subject.user)
  | があなたの
  object
    = link_to  '投稿', post_path(activity.subject.post)
  | に
  object
    = link_to 'コメント', post_path(activity.subject.post, anchor: "comment-#{activity.subject.id}")
  | しました
  .ml-auto
    / lメソッドで日時を読みやすい形に変更する。formatを指定することで、ロケールファイルに書かれている形式で表示させる。
    = l activity.created_at, format: :short

app/views/shared/_error_messages.html.slim
/anyメソッド。errorが一つでもあればtrueを返す。
- if object.errors.any?
  #error_messages.alert.alert-danger
    ul.mb-0
      - object.errors.full_messages.each do |msg|
        li = msg

app/views/shared/_flash_messages.html.slim
/flashで渡されたキーによって色を変える
- flash.each do |key, value|
  /divタグにvalueの文章を入れる
  = content_tag(:div, value, class: "alert alert-#{key}")

app/views/shared/_followed_me.html.slim
/ activity.read?でactivityオブジェクトのread属性がreadかどうか確認できる。enumによって追加されたメソッド。
= link_to read_activity_path(activity), class: "dropdown-item border-bottom #{'read' if activity.read?}", method: :patch do 
  = image_tag activity.subject.follower.avatar.url, class: 'rounded-circle mr-1', size: '30x30'
  object
    = link_to activity.subject.follower.name, user_path(activity.subject.follower)
  | があなたをフォローしました
  .ml-auto
    / lメソッドで日時を読みやすい形に変更する。formatを指定することで、ロケールファイルに書かれている形式で表示させる。
    = l activity.created_at, format: :short

app/views/shared/_header.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-white
  = link_to 'InstaClone', posts_path, class: 'navbar-brand'
  button.navbar-toggler aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarTogglerDemo02" data-toggle="collapse" type="button"
    span.navbar-toggler-icon
  #navbarTogglerDemo02.collapse.navbar-collapse
    = render 'posts/search_form', search_form: @search_form
    ul.navbar-nav.mt-2.mt-lg-0
      li.nav-item
        = link_to new_post_path, class: 'nav-link' do 
          = icon 'far', 'image', class: 'fa-lg'
      li.nav-item
        .dropdown
          a#dropdownMenuButton.nav-link.position-relative href="#" data-toggle="dropdown" aria-expanded="false" aria-haspopup="true"
            = icon 'far', 'heart', class: 'fa-lg'
            = render 'shared/unread_badge'
          #header-activities.dropdown-menu.dropdown-menu-right.m-0.p-0 aria-labelledby="dropdownMenuButton"
            = render 'shared/header_activities'
      li.nav-item
        = link_to user_path(current_user), class: 'nav-link' do 
          = icon 'far', 'user', class: 'fa-lg'
      li.nav-item
        = link_to 'ログアウト', logout_path, class: 'nav-link', method: :delete

app/views/shared/_header_activities.html.slim
- if current_user.activities.present?
  - current_user.activities.recent(10).each do |activity|
    / activity.action_type属性の値によって返すテンプレートを場合分けする。こうすることで、activity.subjectで取得してきたオブジェクトに対して使えるメソッドが決まる。
    = render "shared/#{activity.action_type}", activity: activity
  - if current_user.activities.count > 10
    = link_to 'すべて見る', mypage_activities_path, class: 'dropdown-item justify-content-center'
- else
  .dropdown-item
    | お知らせはありません

app/views/shared/_liked_to_own_post.html.slim
/ activity.read?でactivityオブジェクトのread属性がreadかどうか確認できる。enumによって追加されたメソッド。
= link_to read_activity_path(activity), class: "dropdown-item border-bottom #{'read' if activity.read?}", method: :patch do 
  / activity.subjectで関連するオブジェクトを取得する。
  = image_tag activity.subject.user.avatar.url, class: 'rounded-circle mr-1', size: '30x30'
  object
    = link_to activity.subject.user.name, user_path(activity.subject.user)
  | があなたの
  object
    = link_to  '投稿', post_path(activity.subject.post) 
  | にいいねしました
  .ml-auto
    / lメソッドで日時を読みやすい形に変更する。formatを指定することで、ロケールファイルに書かれている形式で表示させる。
    = l activity.created_at, format: :short

app/views/shared/_unread_badge.html.slim
- if current_user.activities.unread.count > 0
  span.badge.badge-warning.navbar-bagde.position-absolute style='top: 0; right: 0;'
    = current_user.activities.unread.count