config/routes.rb
# == Route Map
#
#                           Prefix Verb   URI Pattern                                                                              Controller#Action
#                letter_opener_web        /letter_opener                                                                           LetterOpenerWeb::Engine
#                      sidekiq_web        /sidekiq                                                                                 Sidekiq::Web
#                             root GET    /                                                                                        posts#index
#                            login GET    /login(.:format)                                                                         sessions#new
#                                  POST   /login(.:format)                                                                         sessions#create
#                           logout DELETE /logout(.:format)                                                                        sessions#destroy
#                            users GET    /users(.:format)                                                                         users#index
#                                  POST   /users(.:format)                                                                         users#create
#                         new_user GET    /users/new(.:format)                                                                     users#new
#                             user GET    /users/:id(.:format)                                                                     users#show
#                    post_comments POST   /posts/:post_id/comments(.:format)                                                       comments#create
#                     edit_comment GET    /comments/:id/edit(.:format)                                                             comments#edit
#                          comment PATCH  /comments/:id(.:format)                                                                  comments#update
#                                  PUT    /comments/:id(.:format)                                                                  comments#update
#                                  DELETE /comments/:id(.:format)                                                                  comments#destroy
#                     search_posts GET    /posts/search(.:format)                                                                  posts#search
#                            posts GET    /posts(.:format)                                                                         posts#index
#                                  POST   /posts(.:format)                                                                         posts#create
#                         new_post GET    /posts/new(.:format)                                                                     posts#new
#                        edit_post GET    /posts/:id/edit(.:format)                                                                posts#edit
#                             post GET    /posts/:id(.:format)                                                                     posts#show
#                                  PATCH  /posts/:id(.:format)                                                                     posts#update
#                                  PUT    /posts/:id(.:format)                                                                     posts#update
#                                  DELETE /posts/:id(.:format)                                                                     posts#destroy
#              edit_mypage_account GET    /mypage/account/edit(.:format)                                                           mypage/accounts#edit
#                   mypage_account PATCH  /mypage/account(.:format)                                                                mypage/accounts#update
#                                  PUT    /mypage/account(.:format)                                                                mypage/accounts#update
#                mypage_activities GET    /mypage/activities(.:format)                                                             mypage/activities#index
# edit_mypage_notification_setting GET    /mypage/notification_setting/edit(.:format)                                              mypage/notification_settings#edit
#      mypage_notification_setting PATCH  /mypage/notification_setting(.:format)                                                   mypage/notification_settings#update
#                                  PUT    /mypage/notification_setting(.:format)                                                   mypage/notification_settings#update
#                            likes POST   /likes(.:format)                                                                         likes#create
#                             like DELETE /likes/:id(.:format)                                                                     likes#destroy
#                    relationships POST   /relationships(.:format)                                                                 relationships#create
#                     relationship DELETE /relationships/:id(.:format)                                                             relationships#destroy
#                    read_activity PATCH  /activities/:id/read(.:format)                                                           activities#read
#               rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
#        rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#               rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
#        update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#             rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create
#
# Routes for LetterOpenerWeb::Engine:
# clear_letters DELETE /clear(.:format)                 letter_opener_web/letters#clear
# delete_letter DELETE /:id(.:format)                   letter_opener_web/letters#destroy
#       letters GET    /                                letter_opener_web/letters#index
#        letter GET    /:id(/:style)(.:format)          letter_opener_web/letters#show
#               GET    /:id/attachments/:file(.:format) letter_opener_web/letters#attachment

# annotateで作成された
Rails.application.routes.draw do
  require 'sidekiq/web'
  # letter_openerを使用した画面の表示のために必要。localhost:3000/letter_openerでメールを確認することができる
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
    # localhost:3000/sidekiqでダッシュボードに繋がる
    mount Sidekiq::Web, at: '/sidekiq'
  end

  root to: 'posts#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users, only: %i[index new create show]
  # shallowオプション。show,edit,update,destroyのようにposts/:post_id/comments/:idを使うアクションのURLをcomments/:idという風に短くする。
  resources :posts, shallow: true do
    resources :comments, only: %i[create edit update destroy]
    # /posts/でurlを始めたい場合にcollectionオプションを使う。/posts/:id/でurlを始めたい場合は、memberオプションを使う。
    collection do
      get 'search'
    end
  end

  # namespaceはurlのパスとディレクトリ構成を変更する。マイページにいろいろ追加するので、マイページ用のディレクトリとurlを作る。
  namespace :mypage do
    # ログインユーザーにとってアカウント編集ページは一つしかないので、単一のresourceを使う。index用のルーティングは存在しない。
    resource :account, only: %i[edit update]
    resources :activities, only: %i[index]
    # 通知設定そのものは、ログインユーザーに対して一つしかないため単一リソースで定義する
    resource :notification_setting, only: %i[edit update]
  end

  resources :likes, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]

  # urlをactivities/:id/readのみに限定するため、onlyで絞る。
  resources :activities, only: [] do
    # memberオプションでactivities/:idというurlが生成される。この場合は、activitiesコントローラーのreadアクションにリクエストを送る。一つしかない場合は、このような書き方ができる。
    patch :read, on: :member
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  body       :string(255)      not null
#  images     :json             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint
#
# Indexes
#
#  index_posts_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Post < ApplicationRecord
  # 引数wordと部分一致するbodyを検索する。('body LIKE ?', "%#{word}%")では?に%word%が代入され、Like検索ができる。
  scope :body_contain, ->(word) { where('body LIKE ?', "%#{word}%") }

  validates :body, presence: true, length: { maximum: 1000 }
  validates :images, presence: true
  # imagesカラムにアップローダークラスをマウントする。carrierwaveの実装にはこの作業が必要。
  mount_uploaders :images, ImageUploader
  belongs_to :user
  # 一つの投稿は複数のコメントを持つ
  has_many :comments, dependent: :destroy
  # 一つの投稿は複数のいいねを持っている
  has_many :likes, dependent: :destroy
  # 投稿にいいねしているユーザーを取得できるメソッド。likesテーブルを経由して、usersテーブルを参照する。
  has_many :like_users, through: :likes, source: :user
  # 一つの投稿には一つの通知しかされないので、has_oneを使用。as: :subjectでポリモーフィック関連づけを行っている。
  has_one :activity, as: :subject, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # sorceryで用意されているメソッド
  before_action :require_login, only: %i[new create edit update destroy]

  def index
    # N+1問題に関係する。ページネーション追加(paramsで現在のページ数を受け取る)
    @posts = if current_user
               # 表示する投稿を自分の投稿とフォローしてるユーザーの投稿のみとする。
               current_user.feed.includes(:user).page(params[:page])
             else
               # 全ての投稿を表示する。
               Post.all.includes(:user).page(params[:page])
             end
    # 登録日が新しい順に５件表示
    @users = User.recent(5)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to posts_path, success: '投稿を作成しました'
    else
      flash.now[:danger] = '投稿作成を失敗しました'
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    # 詳細画面にコメントを表示するためにインスタンス変数追加。
    @comments = @post.comments.includes(:user)
    @comment = Comment.new
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path, success: '投稿を更新しました'
    else
      flash.now[:danger] = '投稿更新を失敗しました'
      render :edit
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    # 削除失敗したら、例外処理が起こる
    @post.destroy!
    redirect_to posts_path, success: '投稿を削除しました'
  end

  def search
    # @search_formはSearchFormsFormのインスタンス。searchメソッドで検索結果を取得する。
    @posts = @search_form.search.includes(:user).page(params[:page])
  end

  private

  def post_params
    # imagesは複数画像を配列形式で受け取るためこのように書き必要がある
    params.require(:post).permit(:body, images: [])
  end
end

app/views/posts/_form.html.slim
= form_with model: post, local: true do |f|
  = render  'shared/error_messages', object: post 
  .form-group
    = f.label :images
    //multiple: trueで複数画像投稿できる
    = f.file_field :images, multiple: true,class: 'form-control'
    - post.images.each do |image|
      = image_tag image.url, size: '100x100'   
  .form-group
    = f.label :body
    = f.text_area :body, class: 'form-control'
  = f.submit nil, class: 'btn btn-primary btn-raised '

app/views/posts/_like.html.slim
= link_to likes_path(post_id: post.id), method: :post, remote: true do
  = icon 'far', 'heart', class: 'fa-lg not-like'

app/views/posts/_like_area.html.slim
/posts/show.html.slimの@postをローカル変数postに代入
div id="like_area-#{post.id}"
  / 投稿がいいねされている場合
  - if current_user.like?(post)
    = render 'unlike', post: post
  / 投稿がいいねされていない場合
  - else
    = render 'like', post: post

app/views/posts/_post.html.slim
.card.mb-5.post
  .card-header
    .d-flex.align-items-center
      = link_to user_path(post.user) do
        = image_tag post.user.avatar.url, size: '40x40', class: 'rounded-circle mr-1'
        = post.user.name
      - if current_user&.own?(post)
        .ml-auto
          = link_to post_path(post), class: 'mr-3', method: :delete, data: { confirm: '本当に削除しますか？' } do
            = icon 'far', 'trash-alt', class: 'fa-lg'
          = link_to edit_post_path(post) do
            = icon 'far', 'edit', class: 'fa-lg'
  = link_to post_path(post) do
    .swiper-container
      .swiper-wrapper
        - post.images.each do |image|
          .swiper-slide
            = image_tag image.url, class: 'card-img-top'
      .swiper-scrollbar
  .card-body
    .card-text
      = post.body

app/views/posts/_search_form.html.slim
/ ActiveRecordを継承してないため、本来はmodelには何も書かないがフォームオブジェクトで書いているため、ActiveRecordを継承したmodelを使用したフォームと同じ書き方をする。
= form_with model: search_form, url: search_posts_path, method: :get, scope: :q, class: 'form-inline my-2 my-lg-0 mr-auto',local: true do |f|
  = f.search_field :body, class: 'form-control mr-sm-2',placeholder: '本文'
  = f.submit 'Search', class: 'btn btn-outline-success my-2 my-sm-0'

app/views/posts/_thumbnail_post.html.slim
.col-md-4.mb-3
  / パーシャル内で使えるインスタンス変数は、パーシャル名と同じ名前の変数が使える。（この場合は、thumbnail_postという変数が使える。）
  = link_to post_path(thumbnail_post), class: 'thumbs' do
    = image_tag thumbnail_post.images.first.url

app/views/posts/_unlike.html.slim
/post_idカラムで検索したいのでfind_by
= link_to like_path(current_user.likes.find_by(post_id: post.id)), method: :delete, remote: true do
  = icon 'fas', 'heart', class: 'fa-lg'

app/views/posts/edit.html.slim
.container
  .row
    .col-md-6.col-12.offset-3
      .card
        .card-body
          = render 'form', post: @post

app/views/posts/index.html.slim
.container
  .row
    .col-md-8.col-12
      - if @posts.present?
        /@postsから自動類推してpostなどの変数を作ってくれる
        = render @posts
      - else
        .text-center.font-weight-bold
          | 投稿がありません
      /ページネーションの実装。aタグにhref='/?page=3'などの属性を付与する。
      = paginate @posts
    .col-md-4.col-12
      / loggen_in。sorceryで用意されたメソッド。
      - if logged_in?
        .profile-box.mb-3
          = image_tag current_user.avatar.url, size: '50x50', class: 'rounded-circle mr-1'
          = link_to current_user.name, edit_mypage_account_path
      .users-box
        .card
          .card-header
            | ユーザー
          .card-body
            / app/views/users/_user.html.slimを使用
            = render @users
          .card-footer
            = link_to 'すべて見る', users_path

app/views/posts/new.html.slim
.container
  .row
    .col-md-6.col-12.offset-md-3
      .card
        .card-body
          = render 'form', post: @post

app/views/posts/search.html.slim
.container
  .row
    .col-md-8.col-12.offset-md-2
      h2.text-center
        / total_countはkaminariによって追加されたメソッド。
        | 検索結果： #{@posts.total_count}件
      = render @posts
      = paginate @posts

app/views/posts/show.html.slim
.post-detail.card
  .image-box
    .swiper-container
      .swiper-wrapper
        - @post.images.each do |image|
          .swiper-slide
            = image_tag image.url
      //スクロールバーの実装
      .swiper-scrollbar
  .image-info-box
    .profile-box.p-3
      .d-flex.align-items-center
        = image_tag @post.user.avatar.url, size: '40x40', class: 'rounded-circle mr-1'
        = @post.user.name
        - if current_user&.own?(@post)
          .ml-auto
            = link_to post_path(@post), class: 'mr-3', method: :delete, data: {confirm: '本当に削除しますか？'} do
              = icon 'far', 'trash-alt', class: 'fa-lg'
            = link_to edit_post_path(@post)  do
              = icon 'far', 'edit', class: 'fa-lg'
        / ログインユーザーかつ自分以外の投稿の場合
        - if current_user && !current_user&.own?(@post)
          .ml-auto
            = render 'like_area', post: @post
    hr.m-0
    .post-body.p-3
      / 投稿の本文
      .row.no-gutters
        .col-2
          = image_tag @post.user.avatar.url, size: '40x40', class: 'rounded-circle'
        .col-10
          = simple_format(@post.body)
      hr
        / コメント一覧
      = render 'comments/comments', comments: @comments
    hr.m-0
    .post-comment.p-3
      = render 'comments/form', post: @post, comment: @comment
#modal-container